const categories=window.TRACE_DATA,categoryTotal=Object.keys(categories).length;let communities=JSON.parse(localStorage.getItem('traceCommunities')||'null')||[{name:'蓝岛康城',region:'海南北部区域',company:'智慧城（海南）生活服务有限公司',cats:6,complete:96,time:'2026-07-26 16:32',user:'张辉玲',status:'已完成'},{name:'蓝岛水岸',region:'海南北部区域',company:'智慧城（海南）生活服务有限公司',cats:5,complete:83,time:'2026-07-24 10:15',user:'王丽',status:'待补充'},{name:'和风兰庭',region:'海甸区域',company:'智慧城（海南）生活服务有限公司',cats:4,complete:68,time:'2026-07-22 14:08',user:'李明',status:'待补充'},{name:'幸福城',region:'海南北部区域',company:'智慧城（海南）生活服务有限公司',cats:6,complete:100,time:'2026-07-20 09:41',user:'陈晓',status:'已完成'}];communities.forEach(c=>{if(c.cats<categoryTotal)c.cats=Math.min(categoryTotal,c.cats+1)});let currentCommunity=communities[0],currentCategory='小区概况',currentSheet=0,sheetPage=1,selectedFile=null;const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));function iconRefresh(){window.lucide&&lucide.createIcons()}
function renderTree(){const q=$('#treeSearch').value.trim(),company='智慧城海南公司',regions=[...new Set(communities.map(c=>c.region))].filter(r=>!q||r.includes(q)||company.includes(q));$('#treeContent').innerHTML=`<button class="tree-node enterprise"><i data-lucide="chevron-down"></i><i data-lucide="building-2"></i><span>智慧城科技（企业）</span></button>${regions.map(r=>`<div class="tree-branch"><button class="tree-node region"><i data-lucide="chevron-down"></i><i data-lucide="map-pin"></i><span>${esc(r)}（片区）</span></button><div class="tree-children"><button class="tree-node company ${$('#regionFilter').value===r?'active':''}" data-region="${esc(r)}"><i data-lucide="briefcase-business"></i><span>${company}</span><em>${communities.filter(c=>c.region===r).length} 个小区</em></button></div></div>`).join('')||'<div class="tree-empty">未找到片区或公司</div>'}`;$$('.tree-node.company').forEach(b=>b.onclick=()=>{$('#regionFilter').value=b.dataset.region;showList();renderCommunities();renderTree()});iconRefresh()}
function renderCommunities(){const q=$('#searchInput').value.trim(),region=$('#regionFilter').value,status=$('#statusFilter').value,list=communities.filter(c=>(!q||c.name.includes(q))&&(!region||c.region===region)&&(!status||c.status===status));$('#communityRows').innerHTML=list.length?list.map(c=>`<tr><td><strong>${esc(c.name)}</strong></td><td>${esc(c.region)}</td><td><div class="category-pills"><span class="mini-pill">${c.cats}/${categoryTotal} 类</span><span>小区概况、财务类、环境类等</span></div></td><td><div class="progress"><div class="bar"><i style="width:${c.complete}%"></i></div><span>${c.complete}%</span></div></td><td>${c.time}</td><td>${esc(c.user)}</td><td><span class="status ${c.status==='已完成'?'done':'pending'}">${c.status}</span></td><td><button class="link-btn view" data-name="${esc(c.name)}">查看</button></td></tr>`).join(''):`<tr><td colspan="8" class="empty-cell">未找到符合条件的小区数据</td></tr>`;$('#resultCount').textContent=`共 ${list.length} 个小区`;$('#totalCount').textContent=list.length;$$('.view').forEach(b=>b.onclick=()=>openDetail(b.dataset.name))}
function openDetail(name){currentCommunity=communities.find(c=>c.name===name)||communities[0];currentSheet=0;sheetPage=1;$('#listView').classList.add('hidden');$('#detailView').classList.remove('hidden');$('#detailName').textContent=currentCommunity.name;renderSummary();renderCategoryTabs();renderSheetNav();renderSheet();renderTree()}function showList(){$('#detailView').classList.add('hidden');$('#listView').classList.remove('hidden');renderTree()}function renderSummary(){const c=currentCommunity;$('#summary').innerHTML=[['所属企业','智慧城科技'],['所属片区',c.region],['所属公司','智慧城海南公司'],['数据分类',`${c.cats} 类`],['数据完整度',`${c.complete}%`],['最后更新',c.time.split(' ')[0]]].map(x=>`<div><span>${x[0]}</span><strong>${esc(x[1])}</strong></div>`).join('')}
function renderCategoryTabs(){$('#categoryTabs').innerHTML=Object.entries(categories).map(([n,d])=>`<button class="category-tab ${n===currentCategory?'active':''}" data-cat="${n}"><strong>${n}</strong><span>${d.rowCount} 条</span></button>`).join('');$$('.category-tab').forEach(b=>b.onclick=()=>{currentCategory=b.dataset.cat;currentSheet=0;sheetPage=1;renderCategoryTabs();renderSheetNav();renderSheet()})}function renderSheetNav(){const d=categories[currentCategory];$('#sheetCount').textContent=`${d.tables.length} 张表`;$('#sheetNav').innerHTML=d.tables.map((s,i)=>`<button class="sheet-nav-item ${i===currentSheet?'active':''}" data-sheet="${i}"><strong>${i+1}</strong><span title="${esc(s.name)}">${esc(s.name)}</span><em>${s.rows.length}</em></button>`).join('');$$('.sheet-nav-item').forEach(b=>b.onclick=()=>{currentSheet=+b.dataset.sheet;sheetPage=1;renderSheetNav();renderSheet()})}
function renderSheet(){
  const d=categories[currentCategory],s=d.tables[currentSheet];
  const isProjectInfo=currentSheet===0||s.name==='项目填报信息',isSummary=s.name.includes('汇总表')||(currentCategory==='小区概况'&&s.name==='小区概况'),isHouseType=currentCategory==='客服类'&&s.name==='小区户型表',canOperate=!isProjectInfo,canDelete=canOperate&&!isSummary;
  const visible=s.columns.map((c,i)=>({c,i})).filter(x=>x.c.trim()!=='序号');
  const sectionPattern=/^[一二三四五六七八九十百]+(?:[\/、][一二三四五六七八九十百]+)*、/;
  const q=$('#recordSearch').value.trim();
  const rows=s.rows.filter(r=>!q||r.join(' ').includes(q));
  let dataSerial=0;
  const entries=rows.map(r=>{const values=r.filter(v=>String(v).trim()),repeatedHeading=values.length>1&&new Set(values).size===1;const title=r.find(v=>sectionPattern.test(String(v).trim()))||(repeatedHeading?values[0]:'');const section=Boolean(title);return{r,title,section,serial:section?null:++dataSerial,sourceIndex:s.rows.indexOf(r)}});
  const size=Math.max(entries.length,1),total=1,pageEntries=entries,sectionCount=entries.filter(x=>x.section).length;
  $('#categoryTitle').textContent=`${currentCategory} · ${s.name}`;
  $('#categoryDesc').textContent=`共 ${dataSerial} 条数据，${sectionCount} 个分组，当前显示第 ${Math.min((sheetPage-1)*size+1,entries.length)}-${Math.min(sheetPage*size,entries.length)} 行`;
  $('#sourceFile').textContent=s.sourceFile||d.file;
  $('#detailHead').innerHTML='<th>序号</th>'+visible.map(x=>`<th>${esc(x.c)}</th>`).join('')+(canOperate?'<th>操作</th>':'');
  const columnCount=visible.length+1+(canOperate?1:0);
  $('#detailRows').innerHTML=pageEntries.length?pageEntries.map(entry=>entry.section?`<tr class="section-row"><td colspan="${columnCount}"><div class="section-row-content"><span>${esc(entry.title)}</span>${isHouseType?`<div class="house-type-section-actions"><button class="link-btn add-house-type" data-row="${entry.sourceIndex}">添加户型</button><button class="link-btn edit-house-section" data-row="${entry.sourceIndex}">编辑</button><button class="link-btn delete-house-section" data-row="${entry.sourceIndex}">删除</button></div>`:''}</div></td></tr>`:`<tr><td>${entry.serial}</td>${visible.map(x=>`<td title="${esc(entry.r[x.i])}">${esc(entry.r[x.i])||'-'}</td>`).join('')}${canOperate?`<td><button class="link-btn edit-row" data-row="${entry.sourceIndex}">编辑</button>${canDelete?`<button class="link-btn delete-row" data-row="${entry.sourceIndex}">删除</button>`:''}</td>`:''}</tr>`).join(''):`<tr><td colspan="${columnCount}" class="empty-cell">当前表中未找到匹配数据</td></tr>`;
  $('#sheetResult').textContent=`共 ${dataSerial} 条数据 · ${sectionCount} 个分组`;
  $('#sheetPage').textContent=`第 ${sheetPage}/${total} 页`;
  $('#prevSheetPage').disabled=sheetPage<=1;$('#nextSheetPage').disabled=sheetPage>=total;
  $('#prevSheetPage').onclick=()=>{sheetPage--;renderSheet()};$('#nextSheetPage').onclick=()=>{sheetPage++;renderSheet()};
  const notes=s.notes||[];$('#sheetNotes').classList.toggle('hidden',!notes.length);$('#sheetNotes').innerHTML=notes.map(note=>`<div><i data-lucide="info"></i><span>${esc(note)}</span></div>`).join('');
  $$('.edit-row').forEach(b=>b.onclick=()=>openEdit(+b.dataset.row));$$('.delete-row').forEach(b=>b.onclick=()=>deleteRow(+b.dataset.row));$$('.add-house-type').forEach(b=>b.onclick=()=>openHouseTypeUnit(+b.dataset.row));$$('.edit-house-section').forEach(b=>b.onclick=()=>openHouseTypeSectionEdit(+b.dataset.row));$$('.delete-house-section').forEach(b=>b.onclick=()=>deleteHouseTypeSection(+b.dataset.row));iconRefresh();
}
function renderDashboard(){const entries=Object.entries(categories),all=entries.reduce((n,[,d])=>n+d.rowCount,0),complete=communities.filter(c=>c.status==='已完成').length;$('#metricGrid').innerHTML=[['小区数量',communities.length,'building-2','#3f8df6'],['填报分类',entries.length,'layers-3','#22a06b'],['有效数据',all.toLocaleString(),'database','#8b5cf6'],['已完成小区',`${complete}/${communities.length}`,'circle-check','#e58a24']].map(x=>`<div class="metric"><span style="background:${x[3]}18;color:${x[3]}"><i data-lucide="${x[2]}"></i></span><div><small>${x[0]}</small><strong>${x[1]}</strong></div></div>`).join('');const max=Math.max(...entries.map(([,d])=>d.rowCount));$('#barChart').innerHTML=entries.map(([n,d])=>`<div class="bar-row"><span>${n}</span><div><i style="width:${Math.max(4,d.rowCount/max*100)}%"></i></div><b>${d.rowCount}</b></div>`).join('');$('#rankList').innerHTML=[...communities].sort((a,b)=>b.complete-a.complete).map(c=>`<div><span>${esc(c.name)}</span><div class="rank-progress"><i style="width:${c.complete}%"></i></div><b>${c.complete}%</b></div>`).join('');$('#categoryOverview').innerHTML=entries.map(([n,d])=>`<div><span>${n}</span><strong>${d.tables.length}<small> 张表</small></strong><em>${d.rowCount} 条记录</em></div>`).join('');iconRefresh()}function switchPage(p){$$('.work-tab').forEach(b=>b.classList.toggle('selected',b.dataset.page===p));$('#dashboardView').classList.toggle('hidden',p!=='dashboard');$('#traceView').classList.toggle('hidden',p!=='trace');if(p==='dashboard')renderDashboard()}
function toast(m){$('#toast span').textContent=m;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}function openUpload(n=currentCommunity.name){$('#uploadCommunity').value=n;$('#uploadCategory').value=currentCategory;$('#uploadModal').classList.remove('hidden');iconRefresh()}function closeUpload(){selectedFile=null;$('#fileInput').value='';$('#filePreview').classList.add('hidden');$('#uploadModal').classList.add('hidden')}function chooseFile(f){if(!f)return;const x=f.name.split('.').pop().toLowerCase();if(!['docx','xlsx','xls','csv'].includes(x)||f.size>20*1024*1024){toast('文件格式不支持或超过 20MB');return}selectedFile=f;$('#filePreview').textContent=`已选择：${f.name} · ${(f.size/1024).toFixed(1)} KB`;$('#filePreview').classList.remove('hidden')}function openEdit(r=0){const s=categories[currentCategory].tables[currentSheet],data=s.rows[r],visible=s.columns.map((c,i)=>({c,i})).filter(x=>x.c.trim()!=='序号');$('#editTitle').textContent=`编辑${currentCategory} · ${s.name}`;$('#editFields').dataset.row=r;$('#editFields').innerHTML=visible.map(x=>`<label>${esc(x.c)}<input value="${esc(data[x.i])}" data-col="${x.i}"></label>`).join('');$('#editModal').classList.remove('hidden');iconRefresh()}function closeEdit(){$('#editModal').classList.add('hidden')}
$('#queryBtn').onclick=renderCommunities;$('#resetBtn').onclick=()=>{$('#searchInput').value='';$('#regionFilter').value='';$('#statusFilter').value='';renderCommunities()};$('#searchInput').onkeydown=e=>e.key==='Enter'&&renderCommunities();$('#refreshBtn').onclick=()=>{renderCommunities();toast('数据已刷新')};$('#backBtn').onclick=showList;$('#uploadBtn').onclick=()=>openUpload('蓝岛康城');$('#detailUploadBtn').onclick=()=>openUpload(currentCommunity.name);$('#editBtn').onclick=()=>openEdit(0);$('#recordSearch').oninput=()=>{sheetPage=1;renderSheet()};$('.sidebar-toggle').onclick=()=>document.body.classList.toggle('collapsed');$('#treeSearch').oninput=renderTree;$$('.work-tab').forEach(b=>b.onclick=()=>switchPage(b.dataset.page));$$('.close-modal').forEach(b=>b.onclick=closeUpload);$$('.close-edit').forEach(b=>b.onclick=closeEdit);$('#fileInput').onchange=e=>chooseFile(e.target.files[0]);const dz=$('#dropzone');['dragenter','dragover'].forEach(v=>dz.addEventListener(v,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(v=>dz.addEventListener(v,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.ondrop=e=>chooseFile(e.dataTransfer.files[0]);$('#confirmUpload').onclick=()=>{if(!selectedFile){toast('请先选择要上传的数据文件');return}const c=communities.find(x=>x.name===$('#uploadCommunity').value);if(c){c.time='2026-07-27 '+new Date().toTimeString().slice(0,5);c.user='张志宣';c.status='已完成';c.complete=Math.max(c.complete,96);localStorage.setItem('traceCommunities',JSON.stringify(communities))}closeUpload();renderCommunities();renderTree();toast(`${$('#uploadCategory').value}数据上传成功`)};$('#saveEdit').onclick=()=>{const s=categories[currentCategory].tables[currentSheet],r=+$('#editFields').dataset.row;$('#editFields input').forEach(i=>s.rows[r][+i.dataset.col]=i.value.trim()||'无');currentCommunity.time='2026-07-27 '+new Date().toTimeString().slice(0,5);currentCommunity.user='张志宣';localStorage.setItem('traceCommunities',JSON.stringify(communities));closeEdit();renderSheet();renderSummary();toast('数据修改已保存')};document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeUpload();closeEdit()}});renderCommunities();renderTree();iconRefresh();
